/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CollectionStatus = "collected" | "disputed" | "issued" | "overdue" | "to_issue";

export type CommessaStatus = "active" | "closed" | "lost" | "offer" | "suspended";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type MilestoneBasis = "fixed" | "percentage";

export type MilestoneType = "advance" | "balance" | "extra" | "interim";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OfferStatus = "draft" | "lost" | "negotiating" | "sent" | "withdrawn" | "won";

export type PersonRole = "admin" | "member";

export type PoStatus = "approved" | "cancelled" | "delivered" | "invoiced" | "issued" | "paid" | "requested";

export type ProjectRole = "data_analysis" | "documentation" | "project_manager" | "site_inspections" | "supervision" | "support";

export type ServiceStatus = "active" | "closed" | "in_certification" | "suspended";

export type SupplierCategory = "accessibility_surveyor" | "acoustics" | "commissioning_agent" | "energy_modeler" | "esg_certification_body" | "external_technical_consultant" | "iaq_survey" | "lighting" | "other" | "testing_laboratory" | "water_analysis";

export type TimeEntrySource = "import" | "manual";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Assignment {
  costRateSnapshot: Numeric;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  estimatedHours: Generated<Numeric>;
  id: Generated<Int8>;
  personId: Int8;
  projectRole: ProjectRole;
  serviceId: Int8;
  soldRateSnapshot: Numeric;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface BillingMilestone {
  basis: MilestoneBasis;
  collectionDate: Timestamp | null;
  collectionStatus: Generated<CollectionStatus>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  description: string | null;
  fixedAmount: Numeric | null;
  id: Generated<Int8>;
  invoiceNumber: string | null;
  issueDate: Timestamp | null;
  percentage: Numeric | null;
  plannedIssueDate: Timestamp | null;
  serviceId: Int8;
  triggerPhaseId: Int8 | null;
  type: MilestoneType;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface Client {
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  id: Generated<Int8>;
  name: string;
  notes: string | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
  vatNumber: string | null;
}

export interface Commessa {
  address: string | null;
  assetName: string | null;
  clientContact: string | null;
  clientId: Int8;
  code: string;
  contractValue: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  endDate: Timestamp | null;
  id: Generated<Int8>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  startDate: Timestamp | null;
  status: Generated<CommessaStatus>;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface HoursForecast {
  etcHours: Numeric;
  id: Generated<Int8>;
  isCurrent: Generated<boolean>;
  notes: string | null;
  personId: Int8;
  quarter: string;
  recordedAt: Generated<Timestamp>;
  recordedById: Int8 | null;
  serviceId: Int8;
}

export interface Level {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  id: Generated<Int8>;
  internalCostRate: Numeric;
  name: string;
  soldRate: Numeric;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface MagicLinkToken {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<Int8>;
  personId: Int8;
  tokenHash: string;
  usedAt: Timestamp | null;
}

export interface Offer {
  amount: Generated<Numeric>;
  assetName: string | null;
  clientId: Int8;
  code: string;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  expectedDecisionDate: Timestamp | null;
  generatedCommessaId: Int8 | null;
  id: Generated<Int8>;
  lossReason: string | null;
  probabilityPct: Numeric | null;
  proposedServices: string | null;
  sentDate: Timestamp | null;
  status: Generated<OfferStatus>;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
  version: Generated<number>;
}

export interface Person {
  active: Generated<boolean>;
  annualAvailableHours: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  email: string;
  id: Generated<Int8>;
  levelId: Int8 | null;
  name: string;
  role: Generated<PersonRole>;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface Phase {
  actualDate: Timestamp | null;
  baselineConfirmed: Generated<boolean>;
  baselineDate: Timestamp | null;
  contractualMilestone: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  expectedDeliverable: string | null;
  hoursQuotaPct: Numeric | null;
  id: Generated<Int8>;
  name: string;
  ownerId: Int8 | null;
  plannedDate: Timestamp | null;
  predecessorPhaseId: Int8 | null;
  progressPct: Generated<Numeric>;
  serviceId: Int8;
  sortOrder: number;
  templateName: string | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface PhaseTemplate {
  contractualMilestone: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  durationDays: number;
  expectedDeliverable: string | null;
  hoursQuotaPct: Numeric;
  id: Generated<Int8>;
  phaseName: string;
  sortOrder: number;
  templateName: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface PurchaseOrder {
  approverId: Int8 | null;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  description: string | null;
  expectedDeliveryDate: Timestamp | null;
  id: Generated<Int8>;
  issueDate: Timestamp | null;
  notes: string | null;
  number: string;
  status: Generated<PoStatus>;
  supplierId: Int8;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface PurchaseOrderLine {
  consultantCost: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  description: string | null;
  id: Generated<Int8>;
  invoicedAmount: Generated<Numeric>;
  phaseRef: string | null;
  purchaseOrderId: Int8;
  rechargedToClient: Generated<Numeric>;
  serviceId: Int8;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface Service {
  code: string;
  commessaId: Int8;
  consultantCostBudget: Generated<Numeric>;
  contractedPrice: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  endDate: Timestamp | null;
  id: Generated<Int8>;
  markup: Generated<Numeric>;
  pmId: Int8 | null;
  serviceTypeId: Int8;
  startDate: Timestamp | null;
  status: Generated<ServiceStatus>;
  templateName: string | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
  variant: string | null;
}

export interface ServiceType {
  active: Generated<boolean>;
  id: Generated<Int8>;
  name: string;
  sortOrder: Generated<number>;
}

export interface Settings {
  defaultMarkup: Generated<Numeric>;
  directorApprovalThreshold: Generated<Numeric>;
  hoursAlertThreshold: Generated<Numeric>;
  id: Generated<number>;
  maxAcceptableDiscount: Generated<Numeric>;
  paymentTermsDays: Generated<number>;
  pmApprovalThreshold: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface Supplier {
  category: SupplierCategory;
  code: string;
  contactName: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  email: string | null;
  id: Generated<Int8>;
  name: string;
  notes: string | null;
  paymentTerms: string | null;
  phone: string | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
  vatNumber: string | null;
}

export interface TimeEntry {
  costRateSnapshot: Numeric;
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  hours: Numeric;
  id: Generated<Int8>;
  month: string;
  personId: Int8;
  phaseId: Int8 | null;
  serviceId: Int8;
  source: Generated<TimeEntrySource>;
  updatedAt: Generated<Timestamp>;
  updatedBy: Int8 | null;
}

export interface VAssignmentMetrics {
  actualHours: Numeric | null;
  alert: string | null;
  assignmentId: Int8 | null;
  consumedPct: Numeric | null;
  costRateSnapshot: Numeric | null;
  eacCost: Numeric | null;
  eacHours: Numeric | null;
  eacValue: Numeric | null;
  estimatedHours: Numeric | null;
  estimatedMargin: Numeric | null;
  etcHours: Numeric | null;
  hoursCost: Numeric | null;
  hoursPrice: Numeric | null;
  personId: Int8 | null;
  projectRole: ProjectRole | null;
  serviceId: Int8 | null;
  soldRateSnapshot: Numeric | null;
  variance: Numeric | null;
}

export interface VBillingMilestoneStatus {
  amount: Numeric | null;
  basis: MilestoneBasis | null;
  collectionDate: Timestamp | null;
  collectionStatus: CollectionStatus | null;
  description: string | null;
  fixedAmount: Numeric | null;
  invoiceNumber: string | null;
  isIssuable: boolean | null;
  issueDate: Timestamp | null;
  milestoneId: Int8 | null;
  percentage: Numeric | null;
  plannedIssueDate: Timestamp | null;
  serviceId: Int8 | null;
  triggerPhaseId: Int8 | null;
  type: MilestoneType | null;
}

export interface VCommessaMetrics {
  clientId: Int8 | null;
  code: string | null;
  collected: Numeric | null;
  commessaId: Int8 | null;
  contractValue: Numeric | null;
  marginPct: Numeric | null;
  marginToComplete: Numeric | null;
  reconciliationOk: boolean | null;
  servicesCount: Int8 | null;
  status: CommessaStatus | null;
  sumOfContractedPrices: Numeric | null;
  toBeInvoiced: Numeric | null;
  totalCostToComplete: Numeric | null;
}

export interface VDashboardBilling {
  cashExposure: Numeric | null;
  issuableAmount: Numeric | null;
  issuableCount: Int8 | null;
  issuedNotCollectedAmount: Numeric | null;
  issuedNotCollectedCount: Int8 | null;
  overdueAmount: Numeric | null;
  overdueCount: Int8 | null;
}

export interface VDashboardByServiceType {
  marginPct: Numeric | null;
  servicesCount: Int8 | null;
  serviceTypeId: Int8 | null;
  serviceTypeName: string | null;
  totalContractedPrice: Numeric | null;
  totalEacHours: Numeric | null;
  totalEstimatedHours: Numeric | null;
  totalMarginToComplete: Numeric | null;
}

export interface VDashboardPortfolio {
  activeServicesCount: Int8 | null;
  avgPlannedMarkup: Numeric | null;
  totalActualHours: Numeric | null;
  totalCalculatedPrice: Numeric | null;
  totalCommittedConsultantCost: Numeric | null;
  totalConsultantCostBudget: Numeric | null;
  totalContractedPrice: Numeric | null;
  totalDiscount: Numeric | null;
  totalEacHours: Numeric | null;
  totalEffectiveHourlyRevenue: Numeric | null;
  totalEffectiveMarkup: Numeric | null;
  totalEstimatedHours: Numeric | null;
  totalEtcHours: Numeric | null;
  totalHoursVariance: Numeric | null;
  totalMarginPct: Numeric | null;
  totalMarginToComplete: Numeric | null;
  totalRechargedToClient: Numeric | null;
}

export interface VDashboardProgress {
  openOffersCount: Int8 | null;
  overduePhasesCount: Int8 | null;
  weightedPipeline: Numeric | null;
}

export interface VMonthlyHoursByPerson {
  hours: Numeric | null;
  month: string | null;
  personId: Int8 | null;
}

export interface VPersonUtilisation {
  annualAvailableHours: Numeric | null;
  eacHoursActive: Numeric | null;
  name: string | null;
  personId: Int8 | null;
  utilisationPct: Numeric | null;
}

export interface VPhaseStatus {
  actualDate: Timestamp | null;
  actualHoursOnPhase: Numeric | null;
  baselineConfirmed: boolean | null;
  baselineDate: Timestamp | null;
  baselineVarianceDays: number | null;
  contractualMilestone: boolean | null;
  daysLate: number | null;
  expectedDeliverable: string | null;
  hoursQuotaPct: Numeric | null;
  indicativeHours: Numeric | null;
  name: string | null;
  ownerId: Int8 | null;
  phaseId: Int8 | null;
  plannedDate: Timestamp | null;
  predecessorPhaseId: Int8 | null;
  progressPct: Numeric | null;
  serviceId: Int8 | null;
  sortOrder: number | null;
  status: string | null;
}

export interface VPurchaseOrderLineMetrics {
  consultantCost: Numeric | null;
  description: string | null;
  invoicedAmount: Numeric | null;
  isCommitted: boolean | null;
  lineId: Int8 | null;
  lineMargin: Numeric | null;
  markupApplied: Numeric | null;
  phaseRef: string | null;
  poStatus: PoStatus | null;
  purchaseOrderId: Int8 | null;
  rechargedToClient: Numeric | null;
  serviceId: Int8 | null;
}

export interface VPurchaseOrderSummary {
  approvalLevel: string | null;
  approverId: Int8 | null;
  expectedDeliveryDate: Timestamp | null;
  isCommitted: boolean | null;
  issueDate: Timestamp | null;
  number: string | null;
  purchaseOrderId: Int8 | null;
  status: PoStatus | null;
  supplierId: Int8 | null;
  totalConsultantCost: Numeric | null;
  totalInvoicedAmount: Numeric | null;
  totalRechargedToClient: Numeric | null;
}

export interface VServiceAlert {
  alert: string | null;
  serviceId: Int8 | null;
}

export interface VServiceMetrics {
  actualHours: Numeric | null;
  calculatedPrice: Numeric | null;
  cashExposure: Numeric | null;
  code: string | null;
  collected: Numeric | null;
  commessaId: Int8 | null;
  committedConsultantCost: Numeric | null;
  consultantCostBudget: Numeric | null;
  consultantCostToComplete: Numeric | null;
  consultantMargin: Numeric | null;
  consultantPrice: Numeric | null;
  contractedPrice: Numeric | null;
  discount: Numeric | null;
  discountPct: Numeric | null;
  eacHours: Numeric | null;
  effectiveHourlyRevenue: Numeric | null;
  effectiveMarkup: Numeric | null;
  estimatedHours: Numeric | null;
  etcHours: Numeric | null;
  hoursConsumedPct: Numeric | null;
  hoursCostToComplete: Numeric | null;
  hoursMargin: Numeric | null;
  hoursPrice: Numeric | null;
  hoursProgressGap: Numeric | null;
  hoursVariance: Numeric | null;
  invoicedToClient: Numeric | null;
  marginPct: Numeric | null;
  marginToComplete: Numeric | null;
  markup: Numeric | null;
  phaseProgressPct: Numeric | null;
  pmId: Int8 | null;
  rechargedToClient: Numeric | null;
  serviceId: Int8 | null;
  serviceTypeId: Int8 | null;
  status: ServiceStatus | null;
  supplierInvoiced: Numeric | null;
  toBeInvoiced: Numeric | null;
  totalCostToComplete: Numeric | null;
}

export interface DB {
  assignment: Assignment;
  billingMilestone: BillingMilestone;
  client: Client;
  commessa: Commessa;
  hoursForecast: HoursForecast;
  level: Level;
  magicLinkToken: MagicLinkToken;
  offer: Offer;
  person: Person;
  phase: Phase;
  phaseTemplate: PhaseTemplate;
  purchaseOrder: PurchaseOrder;
  purchaseOrderLine: PurchaseOrderLine;
  service: Service;
  serviceType: ServiceType;
  settings: Settings;
  supplier: Supplier;
  timeEntry: TimeEntry;
  vAssignmentMetrics: VAssignmentMetrics;
  vBillingMilestoneStatus: VBillingMilestoneStatus;
  vCommessaMetrics: VCommessaMetrics;
  vDashboardBilling: VDashboardBilling;
  vDashboardByServiceType: VDashboardByServiceType;
  vDashboardPortfolio: VDashboardPortfolio;
  vDashboardProgress: VDashboardProgress;
  vMonthlyHoursByPerson: VMonthlyHoursByPerson;
  vPersonUtilisation: VPersonUtilisation;
  vPhaseStatus: VPhaseStatus;
  vPurchaseOrderLineMetrics: VPurchaseOrderLineMetrics;
  vPurchaseOrderSummary: VPurchaseOrderSummary;
  vServiceAlert: VServiceAlert;
  vServiceMetrics: VServiceMetrics;
}
