-- 0002_phase_templates.sql
-- Estratto automaticamente dal foglio TEMPLATE_FASI del file Excel reale
-- (Gestione_Commesse_ESG_v4.xlsm), riga per riga, per evitare errori di
-- trascrizione manuale su percentuali/booleani/durate.
--
-- 14 template reali. hours_quota_pct somma a 1.0 per ciascun template_name
-- (verificato in fase di estrazione).

BEGIN;

INSERT INTO phase_template (template_name, sort_order, phase_name, expected_deliverable, contractual_milestone, duration_days, hours_quota_pct) VALUES
  ('LEED BD+C', 1, 'Preparazione offerta e presentazione', 'Offerta tecnico-economica + scorecard preliminare', false, 15, 0.03),
  ('LEED BD+C', 2, 'Kick-off meeting', 'Verbale kick-off, cronoprogramma, matrice responsabilità', true, 5, 0.02),
  ('LEED BD+C', 3, 'Registrazione progetto su LEED Online', 'Conferma registrazione GBCI', false, 5, 0.02),
  ('LEED BD+C', 4, 'Fase Design – gap analysis e credit strategy', 'Scorecard consolidata + report strategia crediti', true, 45, 0.13),
  ('LEED BD+C', 5, 'Fase Design – redazione documentazione crediti', 'Template LEED compilati e caricati', false, 60, 0.17),
  ('LEED BD+C', 6, 'Design Review submission', 'Ricevuta submission GBCI', true, 5, 0.03),
  ('LEED BD+C', 7, 'Risposta commenti Design Review', 'Documentazione integrativa', false, 25, 0.07),
  ('LEED BD+C', 8, 'Gara Construction – preparazione capitolati LEED', 'Oneri e obblighi appaltatore, CxA plan', false, 25, 0.11),
  ('LEED BD+C', 9, 'Fase Construction – supporto cantiere', 'Verbali sopralluogo, verifica schede materiali', false, 180, 0.13),
  ('LEED BD+C', 10, 'Fase Construction – raccolta dati e collaudi', 'Report commissioning, IAQ, gestione rifiuti', false, 60, 0.11),
  ('LEED BD+C', 11, 'Construction Review submission', 'Ricevuta submission finale', true, 5, 0.03),
  ('LEED BD+C', 12, 'Risposta commenti Construction Review', 'Documentazione integrativa finale', false, 25, 0.07),
  ('LEED BD+C', 13, 'Certificazione ottenuta', 'Certificato LEED + targa', true, 10, 0.05),
  ('LEED BD+C', 14, 'Chiusura commessa e lessons learned', 'Consuntivo economico + archivio documentale', false, 5, 0.03),
  ('LEED ID+C', 1, 'Preparazione offerta e presentazione', 'Offerta tecnico-economica + scorecard preliminare', false, 15, 0.03),
  ('LEED ID+C', 2, 'Kick-off meeting', 'Verbale kick-off, cronoprogramma, matrice responsabilità', true, 5, 0.02),
  ('LEED ID+C', 3, 'Registrazione progetto su LEED Online', 'Conferma registrazione GBCI', false, 5, 0.02),
  ('LEED ID+C', 4, 'Fase Design – gap analysis e credit strategy', 'Scorecard consolidata + report strategia crediti', true, 45, 0.13),
  ('LEED ID+C', 5, 'Fase Design – redazione documentazione crediti', 'Template LEED compilati e caricati', false, 60, 0.17),
  ('LEED ID+C', 6, 'Design Review submission', 'Ricevuta submission GBCI', true, 5, 0.03),
  ('LEED ID+C', 7, 'Risposta commenti Design Review', 'Documentazione integrativa', false, 25, 0.07),
  ('LEED ID+C', 8, 'Gara Construction – preparazione capitolati LEED', 'Oneri e obblighi appaltatore, CxA plan', false, 25, 0.11),
  ('LEED ID+C', 9, 'Fase Construction – supporto cantiere', 'Verbali sopralluogo, verifica schede materiali', false, 180, 0.13),
  ('LEED ID+C', 10, 'Fase Construction – raccolta dati e collaudi', 'Report commissioning, IAQ, gestione rifiuti', false, 60, 0.11),
  ('LEED ID+C', 11, 'Construction Review submission', 'Ricevuta submission finale', true, 5, 0.03),
  ('LEED ID+C', 12, 'Risposta commenti Construction Review', 'Documentazione integrativa finale', false, 25, 0.07),
  ('LEED ID+C', 13, 'Certificazione ottenuta', 'Certificato LEED + targa', true, 10, 0.05),
  ('LEED ID+C', 14, 'Chiusura commessa e lessons learned', 'Consuntivo economico + archivio documentale', false, 5, 0.03),
  ('WELL C&S', 1, 'Preparazione offerta e presentazione', 'Offerta + scorecard WELL preliminare', false, 15, 0.03),
  ('WELL C&S', 2, 'Kick-off meeting', 'Verbale kick-off e matrice responsabilità', true, 5, 0.02),
  ('WELL C&S', 3, 'Registrazione progetto WELL Online', 'Conferma enrollment IWBI', false, 5, 0.02),
  ('WELL C&S', 4, 'Gap analysis Precondition / Optimization', 'Digital Scorecard compilata', true, 40, 0.13),
  ('WELL C&S', 5, 'Fase Design – integrazione requisiti nei progetti', 'Note tecniche per progettisti + verifiche', false, 60, 0.18),
  ('WELL C&S', 6, 'Gara Construction – preparazione capitolati WELL', 'Oneri e obblighi appaltatore', false, 25, 0.09),
  ('WELL C&S', 7, 'Fase Construction – supporto cantiere', 'Verbali sopralluogo, verifica schede materiali', false, 120, 0.12),
  ('WELL C&S', 8, 'Construction Review submission', 'Ricevuta submission finale', false, 15, 0.06),
  ('WELL C&S', 9, 'Preparazione Performance Verification', 'Checklist pre-test e piano campionamenti', false, 20, 0.08),
  ('WELL C&S', 10, 'Performance Verification on-site', 'Report WELL Performance Testing Agent', true, 10, 0.11),
  ('WELL C&S', 11, 'Risposta a Curative Action Plan', 'Piano azioni correttive', false, 20, 0.09),
  ('WELL C&S', 12, 'Certificazione ottenuta', 'Certificato WELL', true, 10, 0.04),
  ('WELL C&S', 13, 'Chiusura e pianificazione ricertificazione', 'Promemoria scadenza 3 anni + consuntivo', false, 5, 0.03),
  ('WELL v.2', 1, 'Preparazione offerta e presentazione', 'Offerta + scorecard WELL preliminare', false, 15, 0.03),
  ('WELL v.2', 2, 'Kick-off meeting', 'Verbale kick-off e matrice responsabilità', true, 5, 0.02),
  ('WELL v.2', 3, 'Registrazione progetto WELL Online', 'Conferma enrollment IWBI', false, 5, 0.02),
  ('WELL v.2', 4, 'Gap analysis Precondition / Optimization', 'Digital Scorecard compilata', true, 40, 0.13),
  ('WELL v.2', 5, 'Fase Design – integrazione requisiti nei progetti', 'Note tecniche per progettisti + verifiche', false, 60, 0.18),
  ('WELL v.2', 6, 'Documentation submission', 'Ricevuta submission IWBI', true, 10, 0.03),
  ('WELL v.2', 7, 'Risposta Documentation Review', 'Documentazione integrativa', false, 25, 0.1),
  ('WELL v.2', 8, 'Gara Construction – preparazione capitolati WELL', 'Oneri e obblighi appaltatore', false, 25, 0.09),
  ('WELL v.2', 9, 'Fase Construction – supporto cantiere', 'Verbali sopralluogo, verifica schede materiali', false, 120, 0.12),
  ('WELL v.2', 10, 'Performance Verification on-site', 'Report WELL Performance Testing Agent', true, 10, 0.12),
  ('WELL v.2', 11, 'Risposta a Curative Action Plan', 'Piano azioni correttive', false, 20, 0.09),
  ('WELL v.2', 12, 'Certificazione ottenuta', 'Certificato WELL', true, 10, 0.04),
  ('WELL v.2', 13, 'Chiusura e pianificazione ricertificazione', 'Promemoria scadenza 3 anni + consuntivo', false, 5, 0.03),
  ('WELL Rating', 1, 'Preparazione offerta', 'Offerta tecnico-economica + pre-valutazione feature', false, 15, 0.06),
  ('WELL Rating', 2, 'Kick-off e selezione delle feature', 'Verbale kick-off + elenco feature target', true, 10, 0.1),
  ('WELL Rating', 3, 'Registrazione su WELL Online', 'Conferma enrollment IWBI', false, 5, 0.03),
  ('WELL Rating', 4, 'Gap analysis sulle feature selezionate', 'Report gap analysis con feature raggiungibili', true, 20, 0.15),
  ('WELL Rating', 5, 'Raccolta evidenze e redazione policy', 'Pacchetto evidenze + policy operative', false, 30, 0.22),
  ('WELL Rating', 6, 'Verifiche on-site e misurazioni', 'Report misurazioni e verifiche documentate', false, 15, 0.12),
  ('WELL Rating', 7, 'Documentation submission', 'Ricevuta submission IWBI', true, 10, 0.05),
  ('WELL Rating', 8, 'Risposta alla review IWBI', 'Documentazione integrativa', false, 20, 0.12),
  ('WELL Rating', 9, 'Rating ottenuto', 'Attestato WELL Rating', true, 10, 0.07),
  ('WELL Rating', 10, 'Chiusura e promemoria rinnovo annuale', 'Consuntivo + scadenzario rinnovo', false, 5, 0.08),
  ('WiredScore', 1, 'Preparazione offerta', 'Offerta tecnico-economica', false, 10, 0.08),
  ('WiredScore', 2, 'Kick-off e raccolta documentazione', 'Checklist documentale', true, 10, 0.12),
  ('WiredScore', 3, 'Building survey / sopralluogo', 'Report sopralluogo infrastrutture', true, 10, 0.15),
  ('WiredScore', 4, 'Assessment e scorecard', 'Scorecard WiredScore preliminare', false, 20, 0.3),
  ('WiredScore', 5, 'Submission a WiredScore', 'Ricevuta submission', true, 5, 0.05),
  ('WiredScore', 6, 'Risposta commenti', 'Documentazione integrativa', false, 15, 0.2),
  ('WiredScore', 7, 'Rating ottenuto e chiusura', 'Certificato + consuntivo', true, 10, 0.1),
  ('BREEAM IU', 1, 'Preparazione offerta', 'Offerta + pre-assessment', false, 15, 0.05),
  ('BREEAM IU', 2, 'Kick-off e registrazione progetto', 'Conferma registrazione BRE', true, 10, 0.05),
  ('BREEAM IU', 3, 'Pre-assessment formale', 'Report pre-assessment con rating atteso', true, 30, 0.15),
  ('BREEAM IU', 4, 'Fase Design – raccolta evidenze', 'Evidence pack Design Stage', false, 60, 0.25),
  ('BREEAM IU', 5, 'Design Stage Assessment submission', 'Ricevuta submission BRE', true, 10, 0.05),
  ('BREEAM IU', 6, 'Fase Construction – monitoraggio', 'Verbali e evidenze di cantiere', false, 150, 0.2),
  ('BREEAM IU', 7, 'Post Construction Assessment submission', 'Evidence pack finale', true, 20, 0.2),
  ('BREEAM IU', 8, 'Certificazione ottenuta e chiusura', 'Certificato BREEAM + consuntivo', true, 10, 0.05),
  ('Fitwel', 1, 'Preparazione offerta', 'Offerta tecnico-economica', false, 10, 0.08),
  ('Fitwel', 2, 'Kick-off e scorecard preliminare', 'Fitwel Scorecard preliminare', true, 15, 0.15),
  ('Fitwel', 3, 'Raccolta evidenze e policy', 'Pacchetto evidenze + policy aziendali', false, 40, 0.35),
  ('Fitwel', 4, 'Submission Fitwel', 'Ricevuta submission CfAD', true, 5, 0.05),
  ('Fitwel', 5, 'Risposta commenti', 'Documentazione integrativa', false, 20, 0.27),
  ('Fitwel', 6, 'Certificazione ottenuta e chiusura', 'Certificato Fitwel + consuntivo', true, 10, 0.1),
  ('CRREM', 1, 'Preparazione offerta', 'Offerta tecnico-economica', false, 10, 0.08),
  ('CRREM', 2, 'Kick-off e raccolta dati energetici', 'Data request list + verbale kick-off', true, 15, 0.2),
  ('CRREM', 3, 'Elaborazione baseline consumi ed emissioni', 'Baseline energetica e di carbonio', false, 20, 0.25),
  ('CRREM', 4, 'Analisi stranding e curve di decarbonizzazione', 'Grafico CRREM con anno di stranding', true, 20, 0.25),
  ('CRREM', 5, 'Definizione scenari di intervento', 'Roadmap di decarbonizzazione con CAPEX', true, 15, 0.15),
  ('CRREM', 6, 'Presentazione e chiusura', 'Report finale + presentazione al cliente', true, 10, 0.07),
  ('Tassonomia UE', 1, 'Preparazione offerta e definizione perimetro', 'Offerta + perimetro asset e attività economiche', false, 15, 0.06),
  ('Tassonomia UE', 2, 'Kick-off e data request', 'Verbale kick-off + lista dati richiesti', true, 10, 0.08),
  ('Tassonomia UE', 3, 'Analisi di ammissibilità (eligibility)', 'Mappatura attività economiche ammissibili', true, 15, 0.1),
  ('Tassonomia UE', 4, 'Verifica criteri di vaglio tecnico', 'Valutazione contributo sostanziale per attività', false, 25, 0.2),
  ('Tassonomia UE', 5, 'Analisi DNSH', 'Verifica assenza di danno significativo sui sei obiettivi', true, 20, 0.18),
  ('Tassonomia UE', 6, 'Verifica garanzie minime di salvaguardia', 'Check su OCSE, diritti umani, fiscalità, concorrenza', false, 10, 0.08),
  ('Tassonomia UE', 7, 'Calcolo KPI di allineamento', 'KPI su fatturato, CapEx e OpEx allineati', true, 15, 0.12),
  ('Tassonomia UE', 8, 'Report e documentazione a supporto', 'Report di allineamento + evidenze', true, 15, 0.12),
  ('Tassonomia UE', 9, 'Presentazione e supporto in fase di audit', 'Presentazione + risposta a quesiti del revisore', false, 10, 0.06),
  ('Climate Risk', 1, 'Preparazione offerta e perimetro asset', 'Offerta + elenco asset da analizzare', false, 15, 0.06),
  ('Climate Risk', 2, 'Kick-off e raccolta dati di asset', 'Data request list + schede tecniche edifici', true, 10, 0.08),
  ('Climate Risk', 3, 'Screening dei pericoli climatici', 'Matrice hazard per localizzazione', false, 15, 0.12),
  ('Climate Risk', 4, 'Analisi di esposizione e vulnerabilita', 'Report esposizione per asset e scenario', true, 25, 0.22),
  ('Climate Risk', 5, 'Valutazione rischi fisici acuti e cronici', 'Quantificazione rischi per orizzonte temporale', true, 20, 0.18),
  ('Climate Risk', 6, 'Analisi dei rischi di transizione', 'Valutazione rischi normativi, di mercato e reputazionali', false, 15, 0.12),
  ('Climate Risk', 7, 'Definizione delle misure di adattamento', 'Piano di adattamento con priorita e CapEx', true, 15, 0.14),
  ('Climate Risk', 8, 'Report finale e allineamento DNSH / CSRD', 'Report conforme ai requisiti di rendicontazione', true, 10, 0.08),
  ('BiodiverCity', 1, 'Preparazione offerta', 'Offerta tecnico-economica + pre-valutazione', false, 15, 0.05),
  ('BiodiverCity', 2, 'Kick-off e raccolta documentazione', 'Verbale kick-off + planimetrie e dati di progetto', true, 10, 0.07),
  ('BiodiverCity', 3, 'Registrazione del progetto', 'Conferma registrazione ente', false, 5, 0.03),
  ('BiodiverCity', 4, 'Diagnosi ecologica del sito', 'Report diagnosi ecologica e stato di fatto', true, 25, 0.18),
  ('BiodiverCity', 5, 'Gap analysis sugli assi di valutazione', 'Scorecard preliminare per asse', true, 20, 0.13),
  ('BiodiverCity', 6, 'Definizione strategia e azioni progettuali', 'Piano azioni per la biodiversita + note ai progettisti', false, 30, 0.17),
  ('BiodiverCity', 7, 'Submission fase Design', 'Ricevuta submission', true, 10, 0.05),
  ('BiodiverCity', 8, 'Risposta ai commenti', 'Documentazione integrativa', false, 20, 0.1),
  ('BiodiverCity', 9, 'Verifica in fase realizzativa', 'Verbali di verifica in cantiere', false, 45, 0.12),
  ('BiodiverCity', 10, 'Submission finale e certificazione', 'Certificato BiodiverCity', true, 15, 0.06),
  ('BiodiverCity', 11, 'Chiusura e piano di monitoraggio', 'Consuntivo + piano monitoraggio pluriennale', false, 5, 0.04),
  ('Consulenza ESG', 1, 'Preparazione offerta e proposta metodologica', 'Offerta + piano di lavoro', false, 15, 0.1),
  ('Consulenza ESG', 2, 'Kick-off e raccolta dati', 'Data request list + verbale kick-off', true, 15, 0.15),
  ('Consulenza ESG', 3, 'Analisi e benchmark', 'Report di analisi intermedio', false, 30, 0.25),
  ('Consulenza ESG', 4, 'Elaborazione deliverable principale', 'Report/strategia ESG', true, 40, 0.3),
  ('Consulenza ESG', 5, 'Presentazione al cliente e revisione', 'Presentazione finale + verbale', true, 10, 0.15),
  ('Consulenza ESG', 6, 'Chiusura commessa', 'Consuntivo economico + archivio', false, 5, 0.05),
  ('Access4You', 1, 'Preparazione offerta e presentazione', 'Offerta tecnico-economica + pre-valutazione livello atteso', false, 15, 0.05),
  ('Access4You', 2, 'Kick-off e raccolta documentazione', 'Verbale kick-off, planimetrie as-built, data request list', true, 10, 0.06),
  ('Access4You', 3, 'Registrazione progetto Access4you', 'Conferma enrollment', false, 5, 0.02),
  ('Access4You', 4, 'Pre-assessment e gap analysis accessibilità', 'Report gap analysis per gruppo di utenza + livello raggiungibile', true, 20, 0.12),
  ('Access4You', 5, 'Preparazione e coordinamento del survey', 'Piano di rilievo, checklist, calendario accessi', false, 10, 0.06),
  ('Access4You', 6, 'Survey on-site e rilievo dati', 'Dataset completo dei rilievi e documentazione fotografica', true, 10, 0.18),
  ('Access4You', 7, 'Elaborazione dati e compilazione scorecard', 'Scorecard Access4you compilata', false, 20, 0.15),
  ('Access4You', 8, 'Submission ad Access4you', 'Ricevuta submission', true, 5, 0.04),
  ('Access4You', 9, 'Risposta a commenti e integrazioni', 'Documentazione integrativa', false, 20, 0.1),
  ('Access4You', 10, 'Definizione azioni migliorative', 'Piano interventi per raggiungere il livello target', false, 20, 0.12),
  ('Access4You', 11, 'Certificazione ottenuta e comunicazione', 'Certificato + materiali di comunicazione per il cliente', true, 10, 0.06),
  ('Access4You', 12, 'Chiusura e pianificazione rinnovo', 'Consuntivo + promemoria scadenza validità', false, 5, 0.04);

COMMIT;
